# org and app are used when using the serverless paid app feature. we can use it for $20 a month.

#org: abigpotostew21
#app: stargaze-rarity
service: stargaze-rarity
frameworkVersion: '3'
custom:
    metadataTopic: ${self:service}-${opt:stage, 'dev'}-metadata-topic #This is the global name of the topic

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x  
  environment:
    METADATA_TOPIC_ARN: arn:aws:sns:${aws:region}:${aws:accountId}:${self:custom.metadataTopic}
    #postgresql
#    POSTGRESQL_HOST: ${self:custom.POSTGRESQL.HOST}
#    POSTGRESQL_PORT: ${self:custom.POSTGRESQL.PORT}
  iamRoleStatements:    
    - Effect: Allow
      Action: sns:Publish`
      Resource:
        - Ref: MetadataTopic  

functions:
  api:
    handler: api.handler
    events:
      - httpApi:
          path: /contracts
          method: get
      - httpApi:
          path: /contracts/{contractId}
          method: post
      - httpApi:
          path: /contracts/{contractId}
          method: get
      - httpApi:
          path: /contracts/{contractId}/rarities
          method: get          
      - httpApi:
          path: /contracts/{contractId}/rarities/{tokenId}
          method: get          
  metadata:
    handler: metadata.handler
    events:
      - httpApi:
          method: POST
          path: /metadata-test
      - sns: 
          arn: 
            Ref: MetadataTopic
          topicName: ${self:custom.metadataTopic}


plugins:
  - serverless-plugin-typescript
  - serverless-offline
#  - serverless-pseudo-parameters

resources:
  Resources:
    MetadataTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.metadataTopic}
      
#  Resources:
#    LambdaRole: ${file(./resource/LambdaRole.yml)}
