#org: abigpotostew21
#app: stargaze-rarity
service: stargaze-rarity
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  environment: 
    #postgresql
#    POSTGRESQL_HOST: ${self:custom.POSTGRESQL.HOST}
#    POSTGRESQL_PORT: ${self:custom.POSTGRESQL.PORT}

functions:
  contract:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /test-create
          method: post
      - httpApi:
          path: /contract
          method: post
      - httpApi:
          method: GET
          path: /contract/{contractId}


plugins:
  - serverless-plugin-typescript
  - serverless-offline
#  - serverless-pseudo-parameters
resources:
#  Resources:
#    LambdaRole: ${file(./resource/LambdaRole.yml)}
