# org and app are used when using the serverless paid app feature. we can use it for $20 a month.

#org: abigpotostew21
#app: stargaze-rarity
service: stargaze-rarity
frameworkVersion: '3'
custom:
  serverless-offline:
    ignoreJWTSignature: true
  metadataTopic: ${self:service}-${opt:stage, 'dev'}-metadata-topic #This is the global name of the topic
  scripts:
    hooks:
      'after:package:createDeploymentArtifacts': >
        printf "[after:package:createDeploymentArtifacts hook] Removing development dependencies " &&
        (cd .serverless && unzip -qq stargaze-rarity.zip -d stargaze-rarity)          && printf "." &&
        (cd .serverless && rm -rf stargaze-rarity/node_modules)                       && printf "." &&
        (cd .serverless/stargaze-rarity && npm install --only=prod > /dev/null 2>&1)  && printf "." &&
        (cd .serverless/stargaze-rarity/ && zip -q -FSr ../stargaze-rarity.zip .)     && printf ".\n" &&
        rm -rf .serverless/stargaze-rarity/ &&
        printf "[after:package:createDeploymentArtifacts hook] Done\n"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x  
  environment:
    METADATA_TOPIC_ARN: arn:aws:sns:${aws:region}:${aws:accountId}:${self:custom.metadataTopic}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: sns:Publish
          Resource:
            - Ref: MetadataTopic
  httpApi:
    cors: true
    authorizers:
      basicAuth:
        functionName: basicAuth
        resultTtlInSeconds: 0
        identitySource:
          - $request.header.Authorization 
        type: request
    # https://www.serverless.com/framework/docs/providers/aws/events/http-api#jwt-authorizers

#  vpc: 
#    securityGroupIds: 
#      - sg-60fddd05
#    subnetIds:
#      - subnet-31f0920b
#      - subnet-8b32c0d2
#      - subnet-b55585c2
#      - subnet-c75510a2
#      - subnet-139c8e3b
#      - subnet-66bc2e6a         

functions:
  basicAuth:
    handler: auth.handler
  api:
    timeout: 20
    handler: api.handler
    events:
      - httpApi:
          path: /contracts
          method: get
      - httpApi:
          path: /contracts/{contractId}
          method: post
          authorizer:
            name: basicAuth
            type: request
      - httpApi:
          path: /contracts/{contractId}
          method: get
      - httpApi:
          path: /contracts/{contractId}/rarities
          method: get
      - httpApi:
          path: /contracts/{contractId}/rarities/{tokenId}
          method: get
  metadata:
    timeout: 900 # 15 minutes, because uncached ipfs files take a while to download
    handler: metadata.handler
    events:
      - httpApi:
          method: POST
          path: /metadata-test
          authorizer:
            name: basicAuth
            type: request
      - sns: 
          arn: 
            Ref: MetadataTopic
          topicName: ${self:custom.metadataTopic}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-scripts

#  - serverless-pseudo-parameters

resources:
  Resources:
    MetadataTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.metadataTopic}
      
#  Resources:
#    LambdaRole: ${file(./resource/LambdaRole.yml)}
